# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target '3DM' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 3DM
  pod 'Parse'
  target '3DMTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '3DMUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
